colorscheme gruvbox

add-highlighter global/ column 80 Error
add-highlighter global/ number-lines -hlcursor -relative
add-highlighter global/ regex \h+$ 0:Error

set-option global aligntab false
set-option global tabstop 4
set-option global indentwidth 4

# Expand tabs by default
hook global WinSetOption filetype=.* %{
    expandtab

    # Expand all tabs to spaces on write
    hook global BufWritePre .* %{
        execute-keys -draft '%@'
    }
}

hook global WinSetOption filetype=html %{
    # Tidy exits with a non-zero exit code if it needed to format, which
    # confuses kakoune, hence `tidy || true`.
    set-option buffer formatcmd 'tidy || true'

    hook global BufWritePre .* %{
        format
    }
}
